### ISSUE TITLE
Issues trying to run tests locally

### ISSUE THREAD

**Issue by caioariede** [mariocesar/sorl-thumbnail#386]
I'm having issues trying to run tests locally. I followed all the steps described here:

http://sorl-thumbnail.readthedocs.org/en/latest/contributing.html#running-testsuit

But I kept receiving errors like the following when running `tox`:

```python
ERROR collecting tests/thumbnail_tests/test_templatetags.py

import file mismatch:
imported module 'tests.thumbnail_tests.test_templatetags' has this __file__ attribute:
  /Users/caio/Projects/sorl-thumbnail/tests/thumbnail_tests/test_templatetags.py
which is not the same as the test file we want to collect:
  /vagrant/tests/thumbnail_tests/test_templatetags.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

Am I missing something?

Thanks

**Comment by mariocesar** [comment]
__pycache__ folders and the pyc firles were probably be generated by your host instead of the vagrant machine, or other wise, so there is probably a permission issue. 

Either delete those files, or run and develop just in your in host or inside the vagrant vm so you make sure those files are always related to the environment

**Comment by caioariede** [comment]
@mariocesar it worked, thanks.

For future references, this is what I did in the host machine:

```bash
find . -name "*.pyc" -delete
find . -name __pycache__ -type d -delete
```
